### ISSUE TITLE
Cuentas GitHub

### ISSUE THREAD

**Issue by dbetm** [Wolfteinter/Club-de-algoritmia-UPIIZ-IPN#1]
Elissa Green
[Comenta tu nombre aquí]
El issue se cierra el 12 de septiembre

**Comment by nathaliarsoto** [comment]
Grecia Nathalia Robles Soto

**Comment by KevBS** [comment]
Kevin Barraza Sandoval

**Comment by Skabe79** [comment]
Carlos Montes Leyva

**Comment by Inosuly** [comment]
Giovanna Inosuli Campos Flores

**Comment by alfredsfdz** [comment]
Luis Alfredo Castañeda Fernández

**Comment by Jorch16** [comment]
Jorge Oziel Rubio Correa

**Comment by MicraBelmont** [comment]
Sandra Mabel Bañuelos Monroy

**Comment by MiroslavaHM** [comment]
Miroslava Hernández Martínez

**Comment by Agus69999** [comment]
Agustín Saldaña Alba

**Comment by alekeyrivas** [comment]
Alejandro Rivas Aranda

**Comment by EICH1** [comment]
Edwin Iván Covarrubias Hernández

**Comment by C7R105** [comment]
Carlos Iván Cerrillo Torres

**Comment by C7R105** [comment]
Carlos Iván Cerrillo Torres

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by VaneMelenciano** [comment]
Vanessa Melenciano Llamas

**Comment by Irvin0121** [comment]
Irvin Adolfo Ramírez Torres

**Comment by 7RM7ND0** [comment]
Armando López

**Comment by Alduadiel** [comment]
Alduadiel Chavez Santacruz

**Comment by V-ac** [comment]
> Verónica Acuña
