### ISSUE TITLE
Registro 2020-2

### ISSUE THREAD

**Issue by dbetm** [Wolfteinter/Club-de-algoritmia-UPIIZ-IPN#3]
Por favor, agrega un comentario y deja tu nombre y carrera :taco:

**Comment by MarlonC-A** [comment]
Marlon Chávez, CECyT

**Comment by C7R105** [comment]
Carlos Iván Cerrillo Torres, sistemas upiiz

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by KevBS** [comment]
Kevin Barraza Sandoval, Sistemas UPIIZ

**Comment by carloshuert** [comment]
Carlos Fernando Huerta Cruz , Sistemas Computacionales

**Comment by VaneMelenciano** [comment]
Vanessa Melenciano Llamas, Ing. en Sistemas.

**Comment by Core-GR** [comment]
Christian Johann Gutiérrez Rodríguez, Ing. Mecatrónica

**Comment by rogerzma** [comment]
Rogelio Zamarripa Martínez. Ingeniería en sistemas computacionales.

**Comment by aldolepa** [comment]
✌️ Aldo Leija pardo
 Ing. Sistemas computacionales
